# Generated by Django 4.1 on 2022-09-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='ComentarioModel',
        ),
        migrations.RenameModel(
            old_name='Text',
            new_name='TextModel',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='UsuarioModel',
        ),
    ]
